networks:
  wordpress-network:
    driver: bridge

services:
  php:
    image: php:8.4-fpm-alpine
    container_name: wpsite_php_${SITE_NAME:-default} # Unique name helps
    restart: unless-stopped
    volumes:
      - ./wp:/var/www/html:delegated
    networks:
      - wordpress-network
    environment:
      # Pass cloud database details via environment variables
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      # You might need other WP constants here too

  nginx:
    image: nginx:stable-alpine
    container_name: wpsite_nginx_${SITE_NAME:-default} # Unique name helps
    restart: unless-stopped
    ports:
      - "${NGINX_HOST_PORT:-8001}:80"
    volumes:
      - ./wp:/var/www/html:delegated
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs/nginx:/var/log/nginx
    networks:
      - wordpress-network
    depends_on:
      - php
