networks:
  wordpress-network:
    driver: bridge

services:
  php:
    image: php:8.4-fpm-alpine
    container_name: wpsite_php_${SITE_NAME:-default}
    restart: unless-stopped
    volumes:
      - ./wp/wordpress:/var/www/html:delegated
    networks:
      - wordpress-network
    environment:
      # Pass cloud database details via environment variables
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSL_CA: ${DB_SSL_CA}
      # You might need other WP constants here too

  nginx:
    image: nginx:stable-alpine
    container_name: wpsite_nginx_${SITE_NAME:-default}
    restart: unless-stopped
    ports:
      - "${NGINX_HOST_PORT:-8001}:80"
    volumes:
      - ./wp/wordpress:/var/www/html:delegated
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs/nginx:/var/log/nginx
    networks:
      - wordpress-network
    depends_on:
      - php
